# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: todoapp
  labels:
    app: todo-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: ikulyk404/todoapp:3.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "150m"
            
        env:
        # Посилання на ConfigMap (todo-app-config)
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: todo-app-config 
              key: PYTHONUNBUFFERED
              
        # Посилання на Secret (todo-app-secret)
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todo-app-secret
              key: SECRET_KEY
              
        ports:
        - containerPort: 8000
        
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        
        livenessProbe:
          httpGet:
            path: api/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5